-- Carritos de ejemplo
INSERT INTO CARRITO (ID_USUARIO, EMAIL_USUARIO) VALUES (1, 'ana.garcia@example.com');
INSERT INTO CARRITO (ID_USUARIO, EMAIL_USUARIO) VALUES (2, 'carlos.lopez@example.com');
INSERT INTO CARRITO (ID_USUARIO, EMAIL_USUARIO) VALUES (3, 'maria.fernandez@example.com');

-- Líneas del carrito 1 (Ana)
INSERT INTO LINEA_CARRITO (CARRITO_ID, ID_ARTICULO, PRECIO_UNITARIO, NUM_UNIDADES, COSTE_LINEA) VALUES (1, 101, 10.50, 3, 31.50);
INSERT INTO LINEA_CARRITO (CARRITO_ID, ID_ARTICULO, PRECIO_UNITARIO, NUM_UNIDADES, COSTE_LINEA) VALUES (1, 102, 5.25, 2, 10.50);

-- Líneas del carrito 2 (Carlos)
INSERT INTO LINEA_CARRITO (CARRITO_ID, ID_ARTICULO, PRECIO_UNITARIO, NUM_UNIDADES, COSTE_LINEA) VALUES (2, 201, 20.00, 1, 20.00);
INSERT INTO LINEA_CARRITO (CARRITO_ID, ID_ARTICULO, PRECIO_UNITARIO, NUM_UNIDADES, COSTE_LINEA) VALUES (2, 202, 15.75, 4, 63.00);
INSERT INTO LINEA_CARRITO (CARRITO_ID, ID_ARTICULO, PRECIO_UNITARIO, NUM_UNIDADES, COSTE_LINEA) VALUES (2, 203, 8.00, 2, 16.00);

-- Líneas del carrito 3 (María)
INSERT INTO LINEA_CARRITO (CARRITO_ID, ID_ARTICULO, PRECIO_UNITARIO, NUM_UNIDADES, COSTE_LINEA) VALUES (3, 301, 50.00, 1, 50.00);
